* NetzplanJS - Lernen und Üben der Netzplantechnik

NetzplanJS ist eine interaktive App, die darauf spezialisiert ist, das Lernen und Üben der Netzplantechnik zu erleichtern. Mit Hilfe von JavaScript ermöglicht es den Nutzern, Netzpläne zu visualisieren, zu erstellen und zu manipulieren, alles in einer benutzerfreundlichen Oberfläche.

** Hauptfunktionen

- [[./Netzplan.js][Netzplan.js]]: Die zentrale Datei, die die Logik für die Erstellung und Manipulation von Netzplänen bereitstellt.
- [[./index.html][index.html]]: Die Haupt-HTML-Datei, die das Grundgerüst der Webseite bildet.
- [[./styles.css][styles.css]]: Enthält die Stildefinitionen für die Webseite.

** Installation und Verwendung

1. Klonen Sie das Repository auf Ihren lokalen Computer.
2. Öffnen Sie die =index.html=-Datei in einem Webbrowser Ihrer Wahl.
3. Beginnen Sie mit dem Erstellen und Manipulieren von Netzplänen über die bereitgestellte Benutzeroberfläche.

** Mitwirken

Möchten Sie zur Weiterentwicklung von NetzplanJS beitragen oder haben Sie Fehler entdeckt? Erstellen Sie einen Pull Request oder melden Sie ein Issue. Jede Hilfe ist willkommen!

** Lizenz

NetzplanJS ist unter der GPLv3 lizenziert. Dies bedeutet:

  - **Rechte**:
    + Sie dürfen das Programm frei verwenden, modifizieren und verteilen.
    + Sie können das Programm unter den Bedingungen der GNU General Public License weitergeben.
    + Sie haben das Recht, auf spätere Versionen der Lizenz zu verweisen, falls diese veröffentlicht werden.
  - **Pflichten**:
    + Bei Weitergabe oder Modifikation des Programms müssen die entsprechenden Lizenzinformationen beibehalten werden.
    + Es dürfen keine zusätzlichen Einschränkungen eingeführt werden, die über das hinausgehen, was die Lizenz vorschreibt.
    + Sie müssen den Empfängern eine Kopie der GNU General Public License zusammen mit dem Programm zur Verfügung stellen.

Für eine detaillierte Beschreibung der Rechte und Pflichten konsultieren Sie bitte die vollständige Lizenz in der [[file:LICENSE][LICENSE]]-Datei im selben Verzeichnis.
